// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6vSbFPkdQpRFz2mQ-Q8Xnlqv9bwofYQg',
    appId: '1:752686860208:web:f7182fc7568f7f527df875',
    messagingSenderId: '752686860208',
    projectId: 'library-management-syste-7938f',
    authDomain: 'library-management-syste-7938f.firebaseapp.com',
    storageBucket: 'library-management-syste-7938f.firebasestorage.app',
    measurementId: 'G-PD5C5ZMDJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf3nGtxexsSL6k0F_ooETskUSIW2lMujM',
    appId: '1:752686860208:android:8d57e9b0dd55ed717df875',
    messagingSenderId: '752686860208',
    projectId: 'library-management-syste-7938f',
    storageBucket: 'library-management-syste-7938f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv8x6PwePOotum3Bk_09HdsmhLfaILUuE',
    appId: '1:752686860208:ios:934f33abcec244fc7df875',
    messagingSenderId: '752686860208',
    projectId: 'library-management-syste-7938f',
    storageBucket: 'library-management-syste-7938f.firebasestorage.app',
    iosClientId: '752686860208-jffildh8g02fgv9redn7pada8h0kkb18.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8x6PwePOotum3Bk_09HdsmhLfaILUuE',
    appId: '1:752686860208:ios:934f33abcec244fc7df875',
    messagingSenderId: '752686860208',
    projectId: 'library-management-syste-7938f',
    storageBucket: 'library-management-syste-7938f.firebasestorage.app',
    iosClientId: '752686860208-jffildh8g02fgv9redn7pada8h0kkb18.apps.googleusercontent.com',
    iosBundleId: 'com.example.problem2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6vSbFPkdQpRFz2mQ-Q8Xnlqv9bwofYQg',
    appId: '1:752686860208:web:01b271ba4abed5297df875',
    messagingSenderId: '752686860208',
    projectId: 'library-management-syste-7938f',
    authDomain: 'library-management-syste-7938f.firebaseapp.com',
    storageBucket: 'library-management-syste-7938f.firebasestorage.app',
    measurementId: 'G-E32YWXJS4P',
  );
}
